name: Feature Request
description: Suggest a new feature or animation preset
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clear description of the feature you'd like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this feature be useful?
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: How would you like this feature to work?
      render: tsx

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New animation preset
        - New component
        - API enhancement
        - Performance improvement
        - Documentation
        - Other
